CREATE OR REPLACE STORAGE INTEGRATION spotify_s3_integration
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::122610497416:role/ACCOUNTADMIN'
STORAGE_ALLOWED_LOCATIONS = ('s3://spotify-data-pipeline-kirthi/');


DESC INTEGRATION spotify_s3_integration;
ALTER STORAGE INTEGRATION spotify_s3_integration
SET STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::122610497416:role/SF_ROLE_S3';